"""add something

Revision ID: 55cebbdddc55
Revises: 0001_baseline
Create Date: 2026-03-31 11:42:08.407841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55cebbdddc55'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_participants_chat_id_user_id_key'), 'chat_participants', schema='messenger', type_='unique')
    op.drop_index(op.f('idx_chat_participants_chat_id'), table_name='chat_participants', schema='messenger')
    op.drop_index(op.f('idx_chat_participants_user_id'), table_name='chat_participants', schema='messenger')
    op.create_unique_constraint('uq_chat_participants_chat_user', 'chat_participants', ['chat_id', 'user_id'], schema='messenger')
    op.drop_constraint(op.f('direct_chat_pairs_user1_id_user2_id_key'), 'direct_chat_pairs', schema='messenger', type_='unique')
    op.create_unique_constraint('uq_direct_chat_pairs_users', 'direct_chat_pairs', ['user1_id', 'user2_id'], schema='messenger')
    op.drop_index(op.f('idx_messages_chat_created_at'), table_name='messages', schema='messenger')
    op.drop_index(op.f('idx_messages_chat_id'), table_name='messages', schema='messenger')
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages', schema='messenger')
    op.drop_index(op.f('idx_messages_expires_at'), table_name='messages', schema='messenger')
    op.drop_index(op.f('idx_messages_is_expired'), table_name='messages', schema='messenger')
    op.drop_index(op.f('idx_messages_sender_id'), table_name='messages', schema='messenger')
    op.drop_index(op.f('idx_messages_status'), table_name='messages', schema='messenger')
    op.create_index(op.f('ix_messenger_messages_chat_id'), 'messages', ['chat_id'], unique=False, schema='messenger')
    op.create_index(op.f('ix_messenger_messages_sender_id'), 'messages', ['sender_id'], unique=False, schema='messenger')
    op.create_index(op.f('ix_messenger_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='messenger')
    op.drop_index(op.f('idx_users_email'), table_name='users', schema='messenger')
    op.drop_index(op.f('idx_users_username'), table_name='users', schema='messenger')
    op.drop_constraint(op.f('users_email_key'), 'users', schema='messenger', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', schema='messenger', type_='unique')
    op.create_index(op.f('ix_messenger_users_email'), 'users', ['email'], unique=True, schema='messenger')
    op.create_index(op.f('ix_messenger_users_username'), 'users', ['username'], unique=True, schema='messenger')
    op.drop_column('users', 'last_seen_at', schema='messenger')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True), schema='messenger')
    op.drop_index(op.f('ix_messenger_users_username'), table_name='users', schema='messenger')
    op.drop_index(op.f('ix_messenger_users_email'), table_name='users', schema='messenger')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], schema='messenger', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], schema='messenger', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False, schema='messenger')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False, schema='messenger')
    op.drop_index(op.f('ix_messenger_refresh_tokens_user_id'), table_name='refresh_tokens', schema='messenger')
    op.drop_index(op.f('ix_messenger_messages_sender_id'), table_name='messages', schema='messenger')
    op.drop_index(op.f('ix_messenger_messages_chat_id'), table_name='messages', schema='messenger')
    op.create_index(op.f('idx_messages_status'), 'messages', ['status'], unique=False, schema='messenger')
    op.create_index(op.f('idx_messages_sender_id'), 'messages', ['sender_id'], unique=False, schema='messenger')
    op.create_index(op.f('idx_messages_is_expired'), 'messages', ['is_expired'], unique=False, schema='messenger')
    op.create_index(op.f('idx_messages_expires_at'), 'messages', ['expires_at'], unique=False, schema='messenger')
    op.create_index(op.f('idx_messages_created_at'), 'messages', ['created_at'], unique=False, schema='messenger')
    op.create_index(op.f('idx_messages_chat_id'), 'messages', ['chat_id'], unique=False, schema='messenger')
    op.create_index(op.f('idx_messages_chat_created_at'), 'messages', ['chat_id', sa.literal_column('created_at DESC')], unique=False, schema='messenger')
    op.drop_constraint('uq_direct_chat_pairs_users', 'direct_chat_pairs', schema='messenger', type_='unique')
    op.create_unique_constraint(op.f('direct_chat_pairs_user1_id_user2_id_key'), 'direct_chat_pairs', ['user1_id', 'user2_id'], schema='messenger', postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_chat_participants_chat_user', 'chat_participants', schema='messenger', type_='unique')
    op.create_index(op.f('idx_chat_participants_user_id'), 'chat_participants', ['user_id'], unique=False, schema='messenger')
    op.create_index(op.f('idx_chat_participants_chat_id'), 'chat_participants', ['chat_id'], unique=False, schema='messenger')
    op.create_unique_constraint(op.f('chat_participants_chat_id_user_id_key'), 'chat_participants', ['chat_id', 'user_id'], schema='messenger', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
